
// // ReportsPage.jsx
// import React, { useRef, useState } from "react";
// import {
//   PieChart,
//   Pie,
//   Cell,
//   BarChart,
//   Bar,
//   ResponsiveContainer,
// } from "recharts";
// import jsPDF from "jspdf";
// import html2canvas from "html2canvas";
// import "../styles/ReportsPage.css";


// const ReportsPage = () => {
//   const reportRef = useRef();

//   // Date filter state
//   const [startDate, setStartDate] = useState("");
//   const [endDate, setEndDate] = useState("");

//   // Example data
//   const managerTableData = [
//     { name: "John Doe", email: "john@example.com", status: "Active", date: "2026-02-10" },
//     { name: "Jane Smith", email: "jane@example.com", status: "Inactive", date: "2026-01-15" },
//   ];

//   const alertsSummary = [
//     { type: "Critical", total: 5, resolved: 3, unresolved: 2, date: "2026-02-05" },
//     { type: "System", total: 12, resolved: 10, unresolved: 2, date: "2026-02-08" },
//   ];

//   const reportsHistory = [
//     { name: "Monthly Summary", type: "PDF", date: "2026-02-01", generatedBy: "Admin" },
//     { name: "Manager Report", type: "CSV", date: "2026-01-25", generatedBy: "Admin" },
//   ];

//   const pieColors = ["#10b981", "#ef4444"];



//   // Filter function by date (fixed for Reports History)
// const filterByDate = (data) => {
//   return data.filter(item => {
//     const itemDate = item.date; // keep as YYYY-MM-DD
//     if (startDate && itemDate < startDate) return false;
//     if (endDate && itemDate > endDate) return false;
//     return true;
//   });
// };


//   const filteredManagers = filterByDate(managerTableData);
//   const filteredAlerts = filterByDate(alertsSummary);
//   const filteredReports = filterByDate(reportsHistory);

//   // Dynamic executive summary totals based on filtered data
//   const totalManagers = filteredManagers.length;
//   const activeManagers = filteredManagers.filter(m => m.status === "Active").length;
//   const inactiveManagers = filteredManagers.filter(m => m.status === "Inactive").length;
//   const criticalAlerts = filteredAlerts.find(a => a.type === "Critical")?.total || 0;
//   const systemAlerts = filteredAlerts.find(a => a.type === "System")?.total || 0;
//   const reportsGenerated = filteredReports.length;

//   const executiveSummary = [
//     { title: "Total Managers", value: totalManagers, color: "#4f46e5" },
//     { title: "Active Managers", value: activeManagers, color: "#10b981" },
//     { title: "Inactive Managers", value: inactiveManagers, color: "#f59e0b" },
//     { title: "Critical Alerts", value: criticalAlerts, color: "#ef4444" },
//     { title: "System Alerts", value: systemAlerts, color: "#3b82f6" },
//     { title: "Reports Generated", value: reportsGenerated, color: "#8b5cf6" },
//   ];

//   // Export full dashboard as PDF
//   const handleGeneratePDF = () => {
//     const input = reportRef.current;
//     html2canvas(input, { scale: 2, useCORS: true }).then((canvas) => {
//       const imgData = canvas.toDataURL("image/png");
//       const pdf = new jsPDF("p", "mm", "a4");
//       const imgProps = pdf.getImageProperties(imgData);
//       const pdfWidth = pdf.internal.pageSize.getWidth();
//       const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
//       pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
//       pdf.save("ReportsDashboard.pdf");
//     });
//   };

//   // Download individual report
//   const handleDownloadReport = (report) => {
//     const pdf = new jsPDF();
//     pdf.text(`Report: ${report.name}`, 10, 10);
//     pdf.text(`Type: ${report.type}`, 10, 20);
//     pdf.text(`Generated Date: ${report.date}`, 10, 30);
//     pdf.text(`Generated By: ${report.generatedBy}`, 10, 40);
//     pdf.save(`${report.name}.pdf`);
//   };

//   return (
//     <div className="reports-page" ref={reportRef}>
//       {/* Header */}
//       <div className="header">
//         <div className="date-filters">
//           <input
//             type="date"
//             value={startDate}
//             onChange={(e) => setStartDate(e.target.value)}
//             className="date-filter"
//           />
//           <input
//             type="date"
//             value={endDate}
//             onChange={(e) => setEndDate(e.target.value)}
//             className="date-filter"
//           />
//         </div>
//         <button onClick={handleGeneratePDF} className="btn">
//           Generate / Export PDF
//         </button>
//       </div>

//       {/* Executive Summary */}
//       <div className="cards-grid">
//         {executiveSummary.map((card) => (
//           <div key={card.title} className="card">
//             <div className="card-title">{card.title}</div>
//             <div className="card-value">{card.value}</div>
//             <div className="card-chart">
//               <ResponsiveContainer width="100%" height={50}>
//                 <BarChart data={[{ value: card.value }]}>
//                   <Bar dataKey="value" fill={card.color} />
//                 </BarChart>
//               </ResponsiveContainer>
//             </div>
//           </div>
//         ))}
//       </div>

//       {/* Manager Registration Table */}
//       <div className="section">
//         <h2>👤 Manager Registration Report</h2>
//         <table className="custom-table">
//           <thead>
//             <tr>
//               <th>Name</th>
//               <th>Email</th>
//               <th>Status</th>
//               <th>Registration Date</th>
//             </tr>
//           </thead>
//           <tbody>
//             {filteredManagers.map((mgr, idx) => (
//               <tr key={idx}>
//                 <td>{mgr.name}</td>
//                 <td>{mgr.email}</td>
//                 <td>{mgr.status}</td>
//                 <td>{mgr.date}</td>
//               </tr>
//             ))}
//           </tbody>
//         </table>
//       </div>

//       {/* Alerts Summary */}
//       <div className="section">
//         <h2>🚨 Alerts Summary</h2>
//         <div className="alerts-grid">
//           {filteredAlerts.map((alert) => (
//             <div key={alert.type} className="card">
//               <div className="card-title">{alert.type} Alerts</div>
//               <div className="card-value">{alert.total}</div>
//               <ResponsiveContainer width="100%" height={100}>
//                 <PieChart>
//                   <Pie
//                     data={[
//                       { name: "Resolved", value: alert.resolved },
//                       { name: "Unresolved", value: alert.unresolved },
//                     ]}
//                     dataKey="value"
//                     innerRadius={20}
//                     outerRadius={40}
//                   >
//                     <Cell fill={pieColors[0]} />
//                     <Cell fill={pieColors[1]} />
//                   </Pie>
//                 </PieChart>
//               </ResponsiveContainer>
//             </div>
//           ))}
//         </div>
//       </div>

//       {/* Reports History Table */}
//       <div className="section">
//         <h2>📁 Reports History</h2>
//         <table className="custom-table">
//           <thead>
//             <tr>
//               <th>Report Name</th>
//               <th>Type</th>
//               <th>Generated Date</th>
//               <th>Generated By</th>
//               <th>Download</th>
//             </tr>
//           </thead>
//           <tbody>
//             {filteredReports.map((report, idx) => (
//               <tr key={idx}>
//                 <td>{report.name}</td>
//                 <td>{report.type}</td>
//                 <td>{report.date}</td>
//                 <td>{report.generatedBy}</td>
//                 <td>
//                   <button
//                     onClick={() => handleDownloadReport(report)}
//                     className="btn"
//                   >
//                     Download
//                   </button>
//                 </td>
//               </tr>
//             ))}
//           </tbody>
//         </table>
//       </div>

//       <div className="bottom-button">
//         <button onClick={handleGeneratePDF} className="btn">
//           Generate / Export PDF
//         </button>
//       </div>
//     </div>
//   );
// };

// export default ReportsPage;


// ReportsPage.jsx
import React, { useRef, useState } from "react";
import {
  PieChart,
  Pie,
  Cell,
  BarChart,
  Bar,
  ResponsiveContainer,
} from "recharts";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import "../styles/ReportsPage.css";
import axios from "axios";
import { useEffect } from "react";


const ReportsPage = () => {
  const reportRef = useRef();

  // Date filter state
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");

   // Reports data from backend
const [managerTableData, setManagerTableData] = useState([]);
const [alertsSummary, setAlertsSummary] = useState([]);
// const [reportsHistory, setReportsHistory] = useState([]);

useEffect(() => {
  fetchReports();
}, []);

const fetchReports = async () => {
  try {
    const res = await axios.get("http://localhost:5000/api/admin/reports");

    setManagerTableData(res.data.managers);
    setAlertsSummary(res.data.alerts);
    // setReportsHistory(res.data.reports);

  } catch (error) {
    console.error("Error fetching reports:", error);
  }
};




  // // Mock Manager Data (Registered + Invited)
  // const managerTableData = [
  //   { name: "John Doe", email: "john@example.com", status: "Active", date: "2026-02-10" },
  //   { name: "Jane Smith", email: "jane@example.com", status: "Inactive", date: "2026-01-15" },

  //   // Invited managers (not registered yet)
  //   { name: "", email: "marametola10@gmail.com", status: "Pending", date: "2026-03-04" },
  //   { name: "", email: "newmanager@example.com", status: "Pending", date: "2026-03-05" },
  // ];

  // const alertsSummary = [
  //   { type: "Critical", total: 5, resolved: 3, unresolved: 2, date: "2026-02-05" },
  //   { type: "System", total: 12, resolved: 10, unresolved: 2, date: "2026-02-08" },
  // ];

  // const reportsHistory = [
  //   { name: "Monthly Summary", type: "PDF", date: "2026-02-01", generatedBy: "Admin" },
  //   { name: "Manager Report", type: "CSV", date: "2026-01-25", generatedBy: "Admin" },
  // ];

  const pieColors = ["#10b981", "#ef4444"];

  // Filter function by date
  const filterByDate = (data) => {
    return data.filter((item) => {
      const itemDate = item.date;
      if (startDate && itemDate < startDate) return false;
      if (endDate && itemDate > endDate) return false;
      return true;
    });
  };

  const filteredManagers = filterByDate(managerTableData);
  const filteredAlerts = filterByDate(alertsSummary);
  // const filteredReports = filterByDate(reportsHistory);

  // Executive Summary
  const totalManagers = filteredManagers.length;
  const activeManagers = filteredManagers.filter(m => m.status === "Active").length;
  const inactiveManagers = filteredManagers.filter(m => m.status === "Inactive").length;
  const pendingManagers = filteredManagers.filter(m => m.status === "Pending").length;

  const criticalAlerts = filteredAlerts.find(a => a.type === "Critical")?.total || 0;
  const systemAlerts = filteredAlerts.find(a => a.type === "System")?.total || 0;
  // const reportsGenerated = filteredReports.length;

  const executiveSummary = [
    { title: "Total Managers", value: totalManagers, color: "#4f46e5" },
    { title: "Active Managers", value: activeManagers, color: "#10b981" },
    { title: "Inactive Managers", value: inactiveManagers, color: "#f59e0b" },
    { title: "Pending Invitations", value: pendingManagers, color: "#f97316" },
    { title: "Critical Alerts", value: criticalAlerts, color: "#ef4444" },
    // { title: "Reports Generated", value: reportsGenerated, color: "#8b5cf6" },
  ];

  // // Export dashboard as PDF
  // const handleGeneratePDF = () => {
  //   const input = reportRef.current;
  //   html2canvas(input, { scale: 2, useCORS: true }).then((canvas) => {
  //     const imgData = canvas.toDataURL("image/png");
  //     const pdf = new jsPDF("p", "mm", "a4");

  //     const imgProps = pdf.getImageProperties(imgData);
  //     const pdfWidth = pdf.internal.pageSize.getWidth();
  //     const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

  //     pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
  //     pdf.save("ReportsDashboard.pdf");

      

  //   });
  // };

    const handleGeneratePDF = async () => {

  const input = reportRef.current;

  html2canvas(input, { scale: 2, useCORS: true }).then(async (canvas) => {

    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "mm", "a4");

    const imgProps = pdf.getImageProperties(imgData);
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

    pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
    pdf.save("ReportsDashboard.pdf");

    // SAVE REPORT HISTORY
    await axios.post("http://localhost:5000/api/admin/save-report", {
      name: "Reports Dashboard"
    });

  });

};
    
  // Download individual report
  const handleDownloadReport = (report) => {
    const pdf = new jsPDF();
    pdf.text(`Report: ${report.name}`, 10, 10);
    pdf.text(`Type: ${report.type}`, 10, 20);
    pdf.text(`Generated Date: ${report.date}`, 10, 30);
    pdf.text(`Generated By: ${report.generatedBy}`, 10, 40);
    pdf.save(`${report.name}.pdf`);
  };

  return (
    <div className="reports-page" ref={reportRef}>

      {/* Header */}
      <div className="header">
        <div className="date-filters">
          <input
            type="date"
            value={startDate}
            onChange={(e) => setStartDate(e.target.value)}
            className="date-filter"
          />

          <input
            type="date"
            value={endDate}
            onChange={(e) => setEndDate(e.target.value)}
            className="date-filter"
          />
        </div>

        <button onClick={handleGeneratePDF} className="btn">
          Generate / Export PDF
        </button>
      </div>

      {/* Executive Summary */}
      <div className="cards-grid">
        {executiveSummary.map((card) => (
          <div key={card.title} className="card">
            <div className="card-title">{card.title}</div>
            <div className="card-value">{card.value}</div>

            <div className="card-chart">
              <ResponsiveContainer width="100%" height={50}>
                <BarChart data={[{ value: card.value }]}>
                  <Bar dataKey="value" fill={card.color} />
                </BarChart>
              </ResponsiveContainer>
            </div>

          </div>
        ))}
      </div>

      {/* Manager Registration Table */}
      <div className="section">
        <h2>👤 Manager Registration Report</h2>
 <div className="table-scroll">
        <table className="custom-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Status</th>
              <th>Date</th>
            </tr>
          </thead>

          <tbody>
            {filteredManagers.map((mgr, idx) => (
              <tr key={idx}>
                <td>{mgr.name || "—"}</td>
                <td>{mgr.email}</td>
                <td>{mgr.status}</td>
                <td>{mgr.date}</td>
              </tr>
            ))}
          </tbody>

        </table>
      </div>
      </div>

      {/* Alerts Summary */}
      <div className="section">
        <h2>🚨 Alerts Summary</h2>

        <div className="alerts-grid">
          {filteredAlerts.map((alert) => (
            <div key={alert.type} className="card">

              <div className="card-title">{alert.type} Alerts</div>
              <div className="card-value">{alert.total}</div>

              <ResponsiveContainer width="100%" height={100}>
                <PieChart>

                  <Pie
                    data={[
                      { name: "Resolved", value: alert.resolved },
                      { name: "Unresolved", value: alert.unresolved },
                    ]}
                    dataKey="value"
                    innerRadius={20}
                    outerRadius={40}
                  >

                    <Cell fill={pieColors[0]} />
                    <Cell fill={pieColors[1]} />

                  </Pie>

                </PieChart>
              </ResponsiveContainer>

            </div>
          ))}
        </div>
      </div>

      {/* Reports History
      <div className="section">
        <h2>📁 Reports History</h2>

        <table className="custom-table">
          <thead>
            <tr>
              <th>Report Name</th>
              <th>Type</th>
              <th>Generated Date</th>
              <th>Generated By</th>
              <th>Download</th>
            </tr>
          </thead>

          <tbody>
            {filteredReports.map((report, idx) => (
              <tr key={idx}>

                <td>{report.name}</td>
                <td>{report.type}</td>
                <td>{report.date}</td>
                <td>{report.generatedBy}</td>

                <td>
                  <button
                    onClick={() => handleDownloadReport(report)}
                    className="btn"
                  >
                    Download
                  </button>
                </td>

              </tr>
            ))}
          </tbody>

        </table>
      </div> */}

      {/* <div className="bottom-button">
        <button onClick={handleGeneratePDF} className="btn">
          Generate / Export PDF
        </button>
      </div> */}

    </div>
  );
};

export default ReportsPage;

